### ISSUE TITLE
Bootstrap 4 end of life is the start of 2023; future Arizona Bootstrap development should use Bootstrap 5

### ISSUE THREAD

**Issue by mmunro-ltrr** [az-digital/arizona-bootstrap#530]
## What is the problem that we want to solve?
Arizona Bootstrap is a collection of overrides and small extensions to Twitter Bootstrap, and includes a complete copy of this upstream version as one of its dependencies. In the last two years, the developers of Twitter Bootstrap have had Version 5 as their primary focus, and have been maintaining but not enhancing Version 4, but Arizona Bootstrap is currently based on v4. Twitter Bootstrap will drop support for v4 at the start of 2023: https://github.com/twbs/release

## Conditions of satisfaction
- [ ] Switch development of Arizona Bootstrap to use Twitter Bootstrap v5.
- [x] Offer a long-term support option for the version of Arizona Bootstrap based on v4, despite its end-of-life status.
- [ ] Investigate whether there can be a common sub-set of the two versions giving identical appearance & behavior on web sites using them.

**Comment by trackleft** [comment]
Notes:
Arizona bootstrap version 2 will be available via CDN URL indefinitely
Arizona bootstrap version 2  docs should have dedicated URL indefinitely
Arizona bootstrap version 3 should contain a shim file for version 2 styles so sites can upgrade quickly

**Comment by trackleft** [comment]
Update build tools to sync docs to version 3 folder
Change version number of arizona bootstrap to version 5

**Comment by trackleft** [comment]
Step 0 Create `2.x` branch and treat `main` as `5.x`
- #605
- #606
Step 1 Bring Arizona Bootstrap version 2 up to speed with upstream
Step 2 In parallel with Step 1 alter build tools to push docs into versioned buckets
Step 3 In parallel with Step 1 and step 2 alter build tools to push package assets into versioned buckets
Step 3 Audit Arizona Bootstrap version 2 to determine what we would like to support
Step 4 Create a release candidate for Arizona Bootstrap 5

**Comment by joeparsons** [comment]
## Resources shared by @mmunro-ltrr in our 2023-08-09 workshop:
- https://drafts.csswg.org/css-variables/
- https://getbootstrap.com/docs/5.3/migration/
- https://getbootstrap.com/docs/5.2/migration/
- https://github.com/az-digital/arizona-bootstrap/pull/528
